// TradePulse item database (v2)
// Pet, egg, and vehicle names verified against the Adopt Me! Wiki
// (adoptme.fandom.com) Pets/Eggs/Vehicles pages and the WikiLists
// "List of Adopt Me! Pets" page -- no invented pet names.
//
// Within each pet rarity tier, most pets start at the SAME baseline
// value (a small number of well-known standouts -- Shadow Dragon,
// Bat Dragon, Blue Dog, etc. -- are bumped higher). Real Adopt Me
// trade values are community-driven and shift daily; nobody, including
// the big value-list sites, has a perfectly authoritative number for
// all ~290 items below. Treat these as an editable starting point.
//
// Pet values are BASE values (Normal, no potions). The Neon / Mega
// Neon / Fly / Ride toggles in the app compute the variant value live.
//
// Want to fix a value or add an item? Edit the object below directly,
// or edit gen_data2.py and regenerate.
const ITEMS = [
  {
    "id": 1,
    "name": "Buffalo",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐃",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 2,
    "name": "Cat",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 3,
    "name": "Dog",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐶",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 4,
    "name": "Otter",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 5,
    "name": "Chicken",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐔",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 6,
    "name": "Robin",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 7,
    "name": "Bandicoot",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 8,
    "name": "Chick",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐥",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 9,
    "name": "Tasmanian Tiger",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐯",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 10,
    "name": "Ground Sloth",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦥",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 11,
    "name": "Stingray",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐟",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 12,
    "name": "Wolpertinger",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐇",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 13,
    "name": "Walrus",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦭",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 14,
    "name": "Ant",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐜",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 15,
    "name": "Mouse",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐭",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 16,
    "name": "Dugong",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐳",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 17,
    "name": "Bali Starling",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 18,
    "name": "Malayan Tapir",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐖",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 19,
    "name": "Maleo Bird",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 20,
    "name": "Liger",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐯",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 21,
    "name": "Mosquito",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦟",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 22,
    "name": "Piranha",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐠",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 23,
    "name": "Flying Fish",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐟",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 24,
    "name": "Beluga Whale",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐳",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 25,
    "name": "Armadillo",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦔",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 26,
    "name": "Coyote",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐺",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 27,
    "name": "Sandfish",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐟",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 28,
    "name": "Garden Snake",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐍",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 29,
    "name": "Urchin",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦔",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 30,
    "name": "Bakeneko",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 31,
    "name": "Burtaur",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐂",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 32,
    "name": "Blue Butterfly",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦋",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 33,
    "name": "Island Tarsier",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 34,
    "name": "Jiggly Jerboa",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🐭",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 35,
    "name": "Rubber Ducky",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.1,
    "demand": 1,
    "emoji": "🦆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 36,
    "name": "Blue Dog",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 55,
    "demand": 1,
    "emoji": "🐶",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 37,
    "name": "Chocolate Labrador",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐶",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 38,
    "name": "Fennec Fox",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦊",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 39,
    "name": "Pink Cat",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 45,
    "demand": 1,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 40,
    "name": "Puma",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 41,
    "name": "Snow Cat",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 42,
    "name": "Meerkat",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦫",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 43,
    "name": "Wild Boar",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐗",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 44,
    "name": "Black Panther",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 45,
    "name": "Capybara",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐹",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 46,
    "name": "Silly Duck",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 47,
    "name": "Drake",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 48,
    "name": "Wolf",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐺",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 49,
    "name": "Dingo",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 50,
    "name": "Pet Rock",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🪨",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 51,
    "name": "Triceratops",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 52,
    "name": "Stegosaurus",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 53,
    "name": "Glyptodon",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦔",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 54,
    "name": "Bat",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦇",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 55,
    "name": "Snowman",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "⛄",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 56,
    "name": "Crab",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 57,
    "name": "Dolphin",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐬",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 58,
    "name": "Kirin",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐉",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 59,
    "name": "Camel",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐫",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 60,
    "name": "Donkey",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🫏",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 61,
    "name": "Poodle",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐩",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 62,
    "name": "Therapy Dog",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐶",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 63,
    "name": "Possum",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 64,
    "name": "Lobster",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦞",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 65,
    "name": "Hermit Crab",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 66,
    "name": "Arctic Tern",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 67,
    "name": "Warthog",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐗",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 68,
    "name": "Quokka",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐹",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 69,
    "name": "Ostrich",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🦤",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 70,
    "name": "Tasmanian Devil",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "😼",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 71,
    "name": "Munchkin Cat",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 72,
    "name": "French Bulldog",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.5,
    "demand": 1,
    "emoji": "🐶",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 73,
    "name": "Beaver",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦫",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 74,
    "name": "Rabbit",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐰",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 75,
    "name": "Elephant",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐘",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 76,
    "name": "Hyena",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐺",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 77,
    "name": "Bunny",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐰",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 78,
    "name": "Snow Puma",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 79,
    "name": "Brown Bear",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐻",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 80,
    "name": "Australian Kelpie",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 81,
    "name": "Cow",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐮",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 82,
    "name": "Pig",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐷",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 83,
    "name": "Swan",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦢",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 84,
    "name": "Polar Bear",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐻‍❄️",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 85,
    "name": "Reindeer",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦌",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 86,
    "name": "Shrew",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 87,
    "name": "Rat",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 88,
    "name": "Emu",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦤",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 89,
    "name": "Monkey",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 90,
    "name": "Rhino",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦏",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 91,
    "name": "Woolly Mammoth",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦣",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 92,
    "name": "Dilophosaurus",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦎",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 93,
    "name": "Pterodactyl",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦅",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 94,
    "name": "Musk Ox",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐂",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 95,
    "name": "Lynx",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐈",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 96,
    "name": "Ox",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐂",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 97,
    "name": "Narwhal",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐋",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 98,
    "name": "Seahorse",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐠",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 99,
    "name": "Merhorse",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐴",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 100,
    "name": "Sasquatch",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦍",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 101,
    "name": "Husky",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 102,
    "name": "Abyssinian Cat",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 103,
    "name": "Red Fox",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦊",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 104,
    "name": "Woodpecker",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 105,
    "name": "Ibex",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐐",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 106,
    "name": "Orangutan",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦧",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 107,
    "name": "Parakeet",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦜",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 108,
    "name": "Zebra",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦓",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 109,
    "name": "Yellow Butterfly",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦋",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 110,
    "name": "Koi Carp",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐟",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 111,
    "name": "Leopard Cat",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 112,
    "name": "Bloodhound",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 113,
    "name": "Moon Rabbit",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐰",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 114,
    "name": "Feesh",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐟",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 115,
    "name": "Ocelot",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 116,
    "name": "Gecko",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦎",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 117,
    "name": "Tarsier",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 118,
    "name": "Goldfish",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐠",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 119,
    "name": "Gorilla",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦍",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 120,
    "name": "Hare",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐇",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 121,
    "name": "Border Collie",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 122,
    "name": "Goose",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦢",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 123,
    "name": "Pudding Cat",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 124,
    "name": "Hippo",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦛",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 125,
    "name": "Leopard Shark",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦈",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 126,
    "name": "Toy Poodle",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐩",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 127,
    "name": "Indian Leopard",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐆",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 128,
    "name": "Oryx",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦌",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 129,
    "name": "Cherub Chipmunk",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐿️",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 130,
    "name": "Bison",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐃",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 131,
    "name": "Nurse Shark",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🦈",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 132,
    "name": "Pilot Gull",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2,
    "demand": 2,
    "emoji": "🐦",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 133,
    "name": "Flamingo",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 26,
    "demand": 3,
    "emoji": "🦩",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 134,
    "name": "Horse",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐴",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 135,
    "name": "Lion",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 20,
    "demand": 3,
    "emoji": "🦁",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 136,
    "name": "Red Panda",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐼",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 137,
    "name": "Koala",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 18,
    "demand": 3,
    "emoji": "🐨",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 138,
    "name": "Dalmatian",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 28,
    "demand": 3,
    "emoji": "🐶",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 139,
    "name": "Hedgehog",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 24,
    "demand": 3,
    "emoji": "🦔",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 140,
    "name": "Toucan",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦜",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 141,
    "name": "Sloth",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦥",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 142,
    "name": "Sabertooth",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐅",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 143,
    "name": "Shiba Inu",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐕",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 144,
    "name": "Panda",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐼",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 145,
    "name": "Penguin",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐧",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 146,
    "name": "Platypus",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦫",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 147,
    "name": "Turkey",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦃",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 148,
    "name": "Yeti",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦣",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 149,
    "name": "Zombie Buffalo",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐃",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 150,
    "name": "Llama",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦙",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 151,
    "name": "Ladybug",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐞",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 152,
    "name": "Frog",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐸",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 153,
    "name": "Ginger Cat",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐱",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 154,
    "name": "Crocodile",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐊",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 155,
    "name": "Albino Bat",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦇",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 156,
    "name": "Arctic Fox",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦊",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 157,
    "name": "Bee",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐝",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 158,
    "name": "Business Monkey",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 159,
    "name": "Deinonychus",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🦖",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 160,
    "name": "Ghost Bunny",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐇",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 161,
    "name": "Starfish",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "⭐",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 162,
    "name": "Toy Monkey",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 163,
    "name": "Lunar Ox",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 3,
    "emoji": "🐂",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 164,
    "name": "Shadow Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 1800,
    "demand": 4,
    "emoji": "🐉",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 165,
    "name": "Bat Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 1500,
    "demand": 4,
    "emoji": "🦇",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 166,
    "name": "Frost Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 650,
    "demand": 4,
    "emoji": "❄️",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 167,
    "name": "Frost Fury",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 600,
    "demand": 4,
    "emoji": "❄️",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 168,
    "name": "Giraffe",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 420,
    "demand": 4,
    "emoji": "🦒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 169,
    "name": "Owl",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 230,
    "demand": 4,
    "emoji": "🦉",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 170,
    "name": "Kitsune",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 230,
    "demand": 4,
    "emoji": "🦊",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 171,
    "name": "Cerberus",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 250,
    "demand": 4,
    "emoji": "🐺",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 172,
    "name": "Parrot",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 190,
    "demand": 4,
    "emoji": "🦜",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 173,
    "name": "Crow",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 170,
    "demand": 4,
    "emoji": "🐦‍⬛",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 174,
    "name": "Evil Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 150,
    "demand": 4,
    "emoji": "🦄",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 175,
    "name": "Diamond Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 320,
    "demand": 4,
    "emoji": "💎",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 176,
    "name": "Diamond Griffin",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 280,
    "demand": 4,
    "emoji": "💎",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 177,
    "name": "Diamond Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 300,
    "demand": 4,
    "emoji": "💎",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 178,
    "name": "Diamond Ladybug",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 260,
    "demand": 4,
    "emoji": "💎",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 179,
    "name": "Albino Monkey",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 130,
    "demand": 4,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 180,
    "name": "Monkey King",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 120,
    "demand": 4,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 181,
    "name": "Ninja Monkey",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 110,
    "demand": 4,
    "emoji": "🐒",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 182,
    "name": "Queen Bee",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 150,
    "demand": 4,
    "emoji": "🐝",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 183,
    "name": "King Bee",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 140,
    "demand": 4,
    "emoji": "🐝",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 184,
    "name": "Griffin",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 95,
    "demand": 4,
    "emoji": "🦅",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 185,
    "name": "Kangaroo",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 110,
    "demand": 4,
    "emoji": "🦘",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 186,
    "name": "T-Rex",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 100,
    "demand": 4,
    "emoji": "🦖",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 187,
    "name": "Golden Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 150,
    "demand": 4,
    "emoji": "🦄",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 188,
    "name": "Golden Griffin",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 140,
    "demand": 4,
    "emoji": "🦅",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 189,
    "name": "Golden Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 160,
    "demand": 4,
    "emoji": "🐲",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 190,
    "name": "Golden Ladybug",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 130,
    "demand": 4,
    "emoji": "🐞",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 191,
    "name": "Golden Penguin",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 120,
    "demand": 4,
    "emoji": "🐧",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 192,
    "name": "Golden Rat",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 110,
    "demand": 4,
    "emoji": "🐀",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 193,
    "name": "Guardian Lion",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 80,
    "demand": 4,
    "emoji": "🦁",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 194,
    "name": "Metal Ox",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 75,
    "demand": 4,
    "emoji": "🐂",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 195,
    "name": "Skele-Rex",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 80,
    "demand": 4,
    "emoji": "🦴",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 196,
    "name": "Snow Owl",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 70,
    "demand": 4,
    "emoji": "🦉",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 197,
    "name": "Turtle",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 65,
    "demand": 4,
    "emoji": "🐢",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 198,
    "name": "Robo Dog",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 60,
    "demand": 4,
    "emoji": "🤖",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 199,
    "name": "Arctic Reindeer",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 60,
    "demand": 4,
    "emoji": "🦌",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 200,
    "name": "Hot Doggo",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 35,
    "demand": 4,
    "emoji": "🌭",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 201,
    "name": "Dodo",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 50,
    "demand": 4,
    "emoji": "🐤",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 202,
    "name": "Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 55,
    "demand": 4,
    "emoji": "🐲",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 203,
    "name": "Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 55,
    "demand": 4,
    "emoji": "🦄",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 204,
    "name": "Bike",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🚲",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 205,
    "name": "Motorcycle",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🏍️",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 206,
    "name": "Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.4,
    "demand": 1,
    "emoji": "🚗",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 207,
    "name": "Offroader",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.5,
    "demand": 1,
    "emoji": "🚙",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 208,
    "name": "Convertible",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.7,
    "demand": 1,
    "emoji": "🚗",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 209,
    "name": "GoKart",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.9,
    "demand": 2,
    "emoji": "🏎️",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 210,
    "name": "Family Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.8,
    "demand": 1,
    "emoji": "🚐",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 211,
    "name": "Classic Helicopter",
    "category": "Vehicle",
    "rarity": null,
    "value": 3.5,
    "demand": 2,
    "emoji": "🚁",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 212,
    "name": "Classic Airplane",
    "category": "Vehicle",
    "rarity": null,
    "value": 4,
    "demand": 2,
    "emoji": "✈️",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 213,
    "name": "Classic Boat",
    "category": "Vehicle",
    "rarity": null,
    "value": 2,
    "demand": 1,
    "emoji": "🚤",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 214,
    "name": "Banana Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 6,
    "demand": 3,
    "emoji": "🚗",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 215,
    "name": "Ice Cream Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 2.5,
    "demand": 2,
    "emoji": "🍦",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 216,
    "name": "Tractor",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.6,
    "demand": 1,
    "emoji": "🚜",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 217,
    "name": "Harvest Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 1,
    "demand": 1,
    "emoji": "🚛",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 218,
    "name": "Snow Plow",
    "category": "Vehicle",
    "rarity": null,
    "value": 1.2,
    "demand": 1,
    "emoji": "🚛",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 219,
    "name": "Tundra Exploration Machine",
    "category": "Vehicle",
    "rarity": null,
    "value": 5,
    "demand": 2,
    "emoji": "🚜",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 220,
    "name": "Old Sailboat",
    "category": "Vehicle",
    "rarity": null,
    "value": 1.5,
    "demand": 1,
    "emoji": "⛵",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 221,
    "name": "Landsailer",
    "category": "Vehicle",
    "rarity": null,
    "value": 3,
    "demand": 2,
    "emoji": "⛵",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 222,
    "name": "Trireme",
    "category": "Vehicle",
    "rarity": null,
    "value": 4,
    "demand": 2,
    "emoji": "🚣",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 223,
    "name": "Witch's Caravan",
    "category": "Vehicle",
    "rarity": null,
    "value": 7,
    "demand": 2,
    "emoji": "🛺",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 224,
    "name": "Hovercraft",
    "category": "Vehicle",
    "rarity": null,
    "value": 8,
    "demand": 2,
    "emoji": "🛸",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 225,
    "name": "Planetary Core Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 12,
    "demand": 3,
    "emoji": "🚗",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 226,
    "name": "Orchid Racer",
    "category": "Vehicle",
    "rarity": null,
    "value": 10,
    "demand": 2,
    "emoji": "🏎️",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 227,
    "name": "RGB Monster Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 15,
    "demand": 3,
    "emoji": "🚙",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 228,
    "name": "RGB UFO",
    "category": "Vehicle",
    "rarity": null,
    "value": 18,
    "demand": 3,
    "emoji": "🛸",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 229,
    "name": "Rocket Sled",
    "category": "Vehicle",
    "rarity": null,
    "value": 6,
    "demand": 2,
    "emoji": "🛷",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 230,
    "name": "Bathtub",
    "category": "Vehicle",
    "rarity": null,
    "value": 1,
    "demand": 1,
    "emoji": "🛁",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 231,
    "name": "Dogmobile",
    "category": "Vehicle",
    "rarity": null,
    "value": 2,
    "demand": 1,
    "emoji": "🚗",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 232,
    "name": "Santa's Sleigh",
    "category": "Vehicle",
    "rarity": null,
    "value": 9,
    "demand": 3,
    "emoji": "🛷",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 233,
    "name": "Pumpkin Carriage",
    "category": "Vehicle",
    "rarity": null,
    "value": 6,
    "demand": 2,
    "emoji": "🎃",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 234,
    "name": "Limo",
    "category": "Vehicle",
    "rarity": null,
    "value": 5,
    "demand": 2,
    "emoji": "🚘",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 235,
    "name": "Luxury Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 5.5,
    "demand": 2,
    "emoji": "🚘",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 236,
    "name": "Bouncy Ball",
    "category": "Toy",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "⚽",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 237,
    "name": "Frisbee",
    "category": "Toy",
    "rarity": null,
    "value": 0.08,
    "demand": 1,
    "emoji": "🥏",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 238,
    "name": "Kite",
    "category": "Toy",
    "rarity": null,
    "value": 0.2,
    "demand": 1,
    "emoji": "🪁",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 239,
    "name": "Pogo Stick",
    "category": "Toy",
    "rarity": null,
    "value": 0.6,
    "demand": 2,
    "emoji": "🪀",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 240,
    "name": "Balloon",
    "category": "Toy",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🎈",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 241,
    "name": "Grappling Hook",
    "category": "Toy",
    "rarity": null,
    "value": 0.9,
    "demand": 2,
    "emoji": "🪝",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 242,
    "name": "Propeller Hat",
    "category": "Toy",
    "rarity": null,
    "value": 0.7,
    "demand": 1,
    "emoji": "🎩",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 243,
    "name": "Skateboard",
    "category": "Toy",
    "rarity": null,
    "value": 0.4,
    "demand": 1,
    "emoji": "🛹",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 244,
    "name": "Yo-Yo",
    "category": "Toy",
    "rarity": null,
    "value": 0.1,
    "demand": 1,
    "emoji": "🪀",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 245,
    "name": "Rattle",
    "category": "Toy",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🧸",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 246,
    "name": "Cloud Rattle",
    "category": "Toy",
    "rarity": null,
    "value": 1.5,
    "demand": 2,
    "emoji": "☁️",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 247,
    "name": "Apple",
    "category": "Food",
    "rarity": null,
    "value": 0.01,
    "demand": 1,
    "emoji": "🍎",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 248,
    "name": "Cake Slice",
    "category": "Food",
    "rarity": null,
    "value": 0.04,
    "demand": 1,
    "emoji": "🍰",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 249,
    "name": "Pizza Slice",
    "category": "Food",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🍕",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 250,
    "name": "Ice Cream Cone",
    "category": "Food",
    "rarity": null,
    "value": 0.04,
    "demand": 1,
    "emoji": "🍦",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 251,
    "name": "Birthday Cake",
    "category": "Food",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🎂",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 252,
    "name": "Donut",
    "category": "Food",
    "rarity": null,
    "value": 0.03,
    "demand": 1,
    "emoji": "🍩",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 253,
    "name": "Taco",
    "category": "Food",
    "rarity": null,
    "value": 0.03,
    "demand": 1,
    "emoji": "🌮",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 254,
    "name": "Sushi Platter",
    "category": "Food",
    "rarity": null,
    "value": 0.2,
    "demand": 1,
    "emoji": "🍣",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 255,
    "name": "Hot Dog",
    "category": "Food",
    "rarity": null,
    "value": 0.03,
    "demand": 1,
    "emoji": "🌭",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 256,
    "name": "Cookie",
    "category": "Food",
    "rarity": null,
    "value": 0.02,
    "demand": 1,
    "emoji": "🍪",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 257,
    "name": "Watermelon Slice",
    "category": "Food",
    "rarity": null,
    "value": 0.02,
    "demand": 1,
    "emoji": "🍉",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 258,
    "name": "Gingerbread Cookie",
    "category": "Food",
    "rarity": null,
    "value": 0.1,
    "demand": 1,
    "emoji": "🍪",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 259,
    "name": "Classic Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "👶",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 260,
    "name": "Twin Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.5,
    "demand": 1,
    "emoji": "👶",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 261,
    "name": "Pet Carriage Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 1.2,
    "demand": 1,
    "emoji": "👶",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 262,
    "name": "Royal Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 2.5,
    "demand": 2,
    "emoji": "👑",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 263,
    "name": "Sports Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.8,
    "demand": 1,
    "emoji": "👶",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 264,
    "name": "Vintage Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 1.0,
    "demand": 1,
    "emoji": "👶",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 265,
    "name": "Cracked Egg",
    "category": "Egg",
    "rarity": null,
    "value": 0.02,
    "demand": 1,
    "emoji": "🥚",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 266,
    "name": "Pet Egg",
    "category": "Egg",
    "rarity": null,
    "value": 0.5,
    "demand": 2,
    "emoji": "🥚",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 267,
    "name": "Royal Egg",
    "category": "Egg",
    "rarity": null,
    "value": 6,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 268,
    "name": "Farm Egg",
    "category": "Egg",
    "rarity": null,
    "value": 1.5,
    "demand": 2,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 269,
    "name": "Aussie Egg",
    "category": "Egg",
    "rarity": null,
    "value": 8,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 270,
    "name": "Safari Egg",
    "category": "Egg",
    "rarity": null,
    "value": 30,
    "demand": 4,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 271,
    "name": "Jungle Egg",
    "category": "Egg",
    "rarity": null,
    "value": 22,
    "demand": 4,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 272,
    "name": "Fossil Egg",
    "category": "Egg",
    "rarity": null,
    "value": 10,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 273,
    "name": "Ocean Egg",
    "category": "Egg",
    "rarity": null,
    "value": 12,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 274,
    "name": "Mythic Egg",
    "category": "Egg",
    "rarity": null,
    "value": 20,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 275,
    "name": "Woodland Egg",
    "category": "Egg",
    "rarity": null,
    "value": 14,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 276,
    "name": "Japan Egg",
    "category": "Egg",
    "rarity": null,
    "value": 16,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 277,
    "name": "Southeast Asia Egg",
    "category": "Egg",
    "rarity": null,
    "value": 16,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 278,
    "name": "Danger Egg",
    "category": "Egg",
    "rarity": null,
    "value": 18,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 279,
    "name": "Urban Egg",
    "category": "Egg",
    "rarity": null,
    "value": 14,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 280,
    "name": "Desert Egg",
    "category": "Egg",
    "rarity": null,
    "value": 16,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 281,
    "name": "Royal Desert Egg",
    "category": "Egg",
    "rarity": null,
    "value": 22,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 282,
    "name": "Garden Egg",
    "category": "Egg",
    "rarity": null,
    "value": 14,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 283,
    "name": "Moon Egg",
    "category": "Egg",
    "rarity": null,
    "value": 18,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 284,
    "name": "Royal Moon Egg",
    "category": "Egg",
    "rarity": null,
    "value": 24,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 285,
    "name": "Aztec Egg",
    "category": "Egg",
    "rarity": null,
    "value": 16,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 286,
    "name": "Royal Aztec Egg",
    "category": "Egg",
    "rarity": null,
    "value": 22,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 287,
    "name": "Endangered Egg",
    "category": "Egg",
    "rarity": null,
    "value": 20,
    "demand": 3,
    "emoji": "🥚",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 288,
    "name": "Fool Egg",
    "category": "Egg",
    "rarity": null,
    "value": 10,
    "demand": 2,
    "emoji": "🥚",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 289,
    "name": "Golden Egg",
    "category": "Egg",
    "rarity": null,
    "value": 60,
    "demand": 4,
    "emoji": "🥚",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 290,
    "name": "Diamond Egg",
    "category": "Egg",
    "rarity": null,
    "value": 100,
    "demand": 4,
    "emoji": "💎",
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 291,
    "name": "Wrapped Doll",
    "category": "Egg",
    "rarity": null,
    "value": 18,
    "demand": 2,
    "emoji": "🎁",
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 292,
    "name": "Christmas Future Egg",
    "category": "Egg",
    "rarity": null,
    "value": 14,
    "demand": 2,
    "emoji": "🎄",
    "variant": false,
    "obtainable": false,
    "notes": ""
  }
];
