// TradePulse item database
// Auto-generated dataset covering Adopt Me pets (every rarity tier), eggs, vehicles,
// strollers, toys, food, gnomes, and other tradable items.
// Pet values are BASE values for the Normal/No-Potion form -- use the Neon/Mega/Fly/Ride
// toggles in the app to compute the variant value automatically.
//
// Values are community-consensus ESTIMATES for relative comparison and shift constantly
// in the real Adopt Me market -- double check big trades against a live value list.
//
// Want to add or correct an item? Just add a new object to this array, or edit a value.
const ITEMS = [
  {
    "id": 1,
    "name": "Shadow Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 1800,
    "demand": 5,
    "emoji": "🐉",
    "egg": "Halloween 2019",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 2,
    "name": "Bat Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 1500,
    "demand": 5,
    "emoji": "🦇",
    "egg": "Halloween 2019",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 3,
    "name": "Frost Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 650,
    "demand": 5,
    "emoji": "❄️",
    "egg": "Christmas 2019",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 4,
    "name": "Giraffe",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 420,
    "demand": 5,
    "emoji": "🦒",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 5,
    "name": "Owl",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 230,
    "demand": 4,
    "emoji": "🦉",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 6,
    "name": "Parrot",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 190,
    "demand": 4,
    "emoji": "🦜",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 7,
    "name": "Crow",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 170,
    "demand": 4,
    "emoji": "🐦‍⬛",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 8,
    "name": "Evil Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 150,
    "demand": 4,
    "emoji": "🦄",
    "egg": "Halloween 2018",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 9,
    "name": "King Bee",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 140,
    "demand": 4,
    "emoji": "🐝",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 10,
    "name": "Queen Bee",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 150,
    "demand": 4,
    "emoji": "🐝",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 11,
    "name": "Griffin",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 95,
    "demand": 3,
    "emoji": "🦅",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 12,
    "name": "Kangaroo",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 110,
    "demand": 3,
    "emoji": "🦘",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 13,
    "name": "Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 60,
    "demand": 3,
    "emoji": "🦄",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 14,
    "name": "Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 55,
    "demand": 3,
    "emoji": "🐲",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 15,
    "name": "Albino Monkey",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 130,
    "demand": 4,
    "emoji": "🐒",
    "egg": "Monkey Fancy Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 16,
    "name": "T-Rex",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 100,
    "demand": 4,
    "emoji": "🦖",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 17,
    "name": "Narwhal",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 90,
    "demand": 4,
    "emoji": "🐋",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 18,
    "name": "Kitsune",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 240,
    "demand": 5,
    "emoji": "🦊",
    "egg": "Lunar New Year",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 19,
    "name": "Cerberus",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 260,
    "demand": 5,
    "emoji": "🐺",
    "egg": "Halloween 2021",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 20,
    "name": "Wyvern",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 150,
    "demand": 4,
    "emoji": "🐉",
    "egg": "Camp Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 21,
    "name": "Dodo",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 120,
    "demand": 3,
    "emoji": "🐤",
    "egg": "Aussie Egg Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 22,
    "name": "Arctic Fox",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 70,
    "demand": 3,
    "emoji": "🦊",
    "egg": "Arctic Shop",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 23,
    "name": "Polar Bear",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 80,
    "demand": 3,
    "emoji": "🐻‍❄️",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 24,
    "name": "Golden Rat",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 200,
    "demand": 4,
    "emoji": "🐀",
    "egg": "Year of the Rat",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 25,
    "name": "Lunar Tiger",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 110,
    "demand": 4,
    "emoji": "🐯",
    "egg": "Year of the Tiger",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 26,
    "name": "Lunar Ox",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 95,
    "demand": 3,
    "emoji": "🐂",
    "egg": "Year of the Ox",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 27,
    "name": "Lunar Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 130,
    "demand": 4,
    "emoji": "🐉",
    "egg": "Year of the Dragon",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 28,
    "name": "Lunar Snake",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 85,
    "demand": 3,
    "emoji": "🐍",
    "egg": "Year of the Snake",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 29,
    "name": "Phoenix",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 220,
    "demand": 5,
    "emoji": "🔥",
    "egg": "Star Rewards",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 30,
    "name": "Pegasus",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 160,
    "demand": 4,
    "emoji": "🦄",
    "egg": "Mythic Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 31,
    "name": "Diamond Unicorn",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 300,
    "demand": 4,
    "emoji": "💎",
    "egg": "Test Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 32,
    "name": "Diamond Griffin",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 280,
    "demand": 4,
    "emoji": "💎",
    "egg": "Test Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 33,
    "name": "Diamond Dragon",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 320,
    "demand": 4,
    "emoji": "💎",
    "egg": "Test Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 34,
    "name": "Mimic Octopus",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 175,
    "demand": 4,
    "emoji": "🐙",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 35,
    "name": "Cyber Wolf",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 140,
    "demand": 4,
    "emoji": "🐺",
    "egg": "Cyber Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 36,
    "name": "Galaxy Stallion",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 260,
    "demand": 4,
    "emoji": "🌌",
    "egg": "Galaxy Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 37,
    "name": "Robo Dog",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 100,
    "demand": 3,
    "emoji": "🤖",
    "egg": "Cyber Shop",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 38,
    "name": "Triceratops",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 75,
    "demand": 3,
    "emoji": "🦕",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 39,
    "name": "Spinosaurus",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 85,
    "demand": 3,
    "emoji": "🦕",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 40,
    "name": "Mammoth",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 65,
    "demand": 3,
    "emoji": "🦣",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 41,
    "name": "Cow",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 200,
    "demand": 5,
    "emoji": "🐮",
    "egg": "Farm Egg Limited",
    "variant": true,
    "obtainable": false,
    "notes": "Preppy collector favorite"
  },
  {
    "id": 42,
    "name": "Pudding Cat",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 190,
    "demand": 5,
    "emoji": "🐱",
    "egg": "Bakery Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 43,
    "name": "Blue Dog",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 350,
    "demand": 5,
    "emoji": "🐶",
    "egg": "Starter Pet 2018",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable; technically Uncommon rarity"
  },
  {
    "id": 44,
    "name": "Pink Cat",
    "category": "Pet",
    "rarity": "Legendary",
    "value": 340,
    "demand": 5,
    "emoji": "🐱",
    "egg": "Starter Pet 2018",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable; technically Uncommon rarity"
  },
  {
    "id": 45,
    "name": "Koala",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 18,
    "demand": 3,
    "emoji": "🐨",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 46,
    "name": "Pterodactyl",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 20,
    "demand": 3,
    "emoji": "🦅",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 47,
    "name": "Anglerfish",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 15,
    "demand": 3,
    "emoji": "🐟",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 48,
    "name": "Tiger",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 22,
    "demand": 3,
    "emoji": "🐅",
    "egg": "Monkey Fancy Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 49,
    "name": "Snow Cat",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 28,
    "demand": 4,
    "emoji": "🐱",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 50,
    "name": "Reindeer",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 26,
    "demand": 3,
    "emoji": "🦌",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 51,
    "name": "Sugar Glider",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 19,
    "demand": 3,
    "emoji": "🐿️",
    "egg": "Lunar New Year",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 52,
    "name": "Lunar Rabbit",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 24,
    "demand": 3,
    "emoji": "🐰",
    "egg": "Year of the Rabbit",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 53,
    "name": "Dalmatian",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 30,
    "demand": 4,
    "emoji": "🐶",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 54,
    "name": "Flamingo",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 27,
    "demand": 4,
    "emoji": "🦩",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 55,
    "name": "Hedgehog",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 26,
    "demand": 4,
    "emoji": "🦔",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 56,
    "name": "Hyena",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 21,
    "demand": 3,
    "emoji": "🐺",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 57,
    "name": "Elephant",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 23,
    "demand": 3,
    "emoji": "🐘",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 58,
    "name": "Lion",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 20,
    "demand": 3,
    "emoji": "🦁",
    "egg": "Monkey Fancy Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 59,
    "name": "Liger",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 17,
    "demand": 3,
    "emoji": "🐯",
    "egg": "Monkey Fancy Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 60,
    "name": "Crab",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 12,
    "demand": 2,
    "emoji": "🦀",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 61,
    "name": "Snow Leopard",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 18,
    "demand": 3,
    "emoji": "🐆",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 62,
    "name": "Arctic Reindeer",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 19,
    "demand": 3,
    "emoji": "🦌",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 63,
    "name": "Christmas Crab",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 16,
    "demand": 2,
    "emoji": "🦀",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 64,
    "name": "Bat",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 15,
    "demand": 3,
    "emoji": "🦇",
    "egg": "Halloween Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 65,
    "name": "Black Panther",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 22,
    "demand": 3,
    "emoji": "🐆",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 66,
    "name": "Red Panda",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 19,
    "demand": 3,
    "emoji": "🐼",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 67,
    "name": "King Cobra",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 17,
    "demand": 2,
    "emoji": "🐍",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 68,
    "name": "Toucan",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 16,
    "demand": 2,
    "emoji": "🦜",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 69,
    "name": "Cyber Cat",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 21,
    "demand": 3,
    "emoji": "🤖",
    "egg": "Cyber Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 70,
    "name": "Galaxy Wolf",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 25,
    "demand": 3,
    "emoji": "🌌",
    "egg": "Galaxy Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 71,
    "name": "Boxer",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 14,
    "demand": 2,
    "emoji": "🐶",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 72,
    "name": "Polar Bear Cub",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 18,
    "demand": 3,
    "emoji": "🐻‍❄️",
    "egg": "Arctic Shop",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 73,
    "name": "Phoenix Chick",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 20,
    "demand": 3,
    "emoji": "🔥",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 74,
    "name": "Buffalo",
    "category": "Pet",
    "rarity": "Ultra-Rare",
    "value": 13,
    "demand": 2,
    "emoji": "🐃",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 75,
    "name": "Platypus",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.5,
    "demand": 2,
    "emoji": "🦫",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 76,
    "name": "Saber-Tooth Tiger",
    "category": "Pet",
    "rarity": "Rare",
    "value": 5,
    "demand": 2,
    "emoji": "🐅",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 77,
    "name": "King Crab",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4,
    "demand": 2,
    "emoji": "🦀",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 78,
    "name": "Horse",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.5,
    "demand": 2,
    "emoji": "🐴",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 79,
    "name": "Crown Bunny",
    "category": "Pet",
    "rarity": "Rare",
    "value": 5.5,
    "demand": 2,
    "emoji": "🐇",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 80,
    "name": "Snow Owl",
    "category": "Pet",
    "rarity": "Rare",
    "value": 6,
    "demand": 3,
    "emoji": "🦉",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 81,
    "name": "Mistletoe Fox",
    "category": "Pet",
    "rarity": "Rare",
    "value": 5.5,
    "demand": 2,
    "emoji": "🦊",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 82,
    "name": "Lunar Ox Calf",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.8,
    "demand": 2,
    "emoji": "🐂",
    "egg": "Year of the Ox",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 83,
    "name": "Stegosaurus",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.2,
    "demand": 2,
    "emoji": "🦕",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 84,
    "name": "Turtle",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3,
    "demand": 2,
    "emoji": "🐢",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 85,
    "name": "Bearded Dragon",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.6,
    "demand": 2,
    "emoji": "🦎",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 86,
    "name": "Husky",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.8,
    "demand": 2,
    "emoji": "🐶",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 87,
    "name": "Pig (Fancy)",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.4,
    "demand": 2,
    "emoji": "🐷",
    "egg": "Monkey Fancy Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 88,
    "name": "Ostrich",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4,
    "demand": 2,
    "emoji": "🦤",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 89,
    "name": "Zebra",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.4,
    "demand": 2,
    "emoji": "🦓",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 90,
    "name": "Cheetah",
    "category": "Pet",
    "rarity": "Rare",
    "value": 5,
    "demand": 2,
    "emoji": "🐆",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 91,
    "name": "Monkey",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.2,
    "demand": 2,
    "emoji": "🐒",
    "egg": "Monkey Fancy Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 92,
    "name": "Frog",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2.8,
    "demand": 2,
    "emoji": "🐸",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 93,
    "name": "Sloth",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.5,
    "demand": 2,
    "emoji": "🦥",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 94,
    "name": "Gecko",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3,
    "demand": 2,
    "emoji": "🦎",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 95,
    "name": "Goat",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2.6,
    "demand": 1,
    "emoji": "🐐",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 96,
    "name": "Donkey",
    "category": "Pet",
    "rarity": "Rare",
    "value": 2.4,
    "demand": 1,
    "emoji": "🐴",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 97,
    "name": "Snake (Lunar)",
    "category": "Pet",
    "rarity": "Rare",
    "value": 4.2,
    "demand": 2,
    "emoji": "🐍",
    "egg": "Year of the Snake",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 98,
    "name": "Cyber Pup",
    "category": "Pet",
    "rarity": "Rare",
    "value": 5,
    "demand": 2,
    "emoji": "🤖",
    "egg": "Cyber Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 99,
    "name": "Galaxy Fox",
    "category": "Pet",
    "rarity": "Rare",
    "value": 5.6,
    "demand": 2,
    "emoji": "🌌",
    "egg": "Galaxy Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 100,
    "name": "Seal",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.6,
    "demand": 2,
    "emoji": "🦭",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 101,
    "name": "Otter",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.4,
    "demand": 2,
    "emoji": "🦦",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 102,
    "name": "Penguin",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.2,
    "demand": 2,
    "emoji": "🐧",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 103,
    "name": "Anteater",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3,
    "demand": 1,
    "emoji": "🐜",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 104,
    "name": "Wallaby",
    "category": "Pet",
    "rarity": "Rare",
    "value": 3.5,
    "demand": 1,
    "emoji": "🦘",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 105,
    "name": "Sheep",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.9,
    "demand": 1,
    "emoji": "🐑",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 106,
    "name": "Royal Cat",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.4,
    "demand": 2,
    "emoji": "🐱",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 107,
    "name": "Sea Turtle",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.1,
    "demand": 1,
    "emoji": "🐢",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 108,
    "name": "Mammoth Calf",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.3,
    "demand": 1,
    "emoji": "🦣",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 109,
    "name": "Spotted Gecko",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.0,
    "demand": 1,
    "emoji": "🦎",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 110,
    "name": "Toad",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.8,
    "demand": 1,
    "emoji": "🐸",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 111,
    "name": "Kitten",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.2,
    "demand": 2,
    "emoji": "🐱",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 112,
    "name": "Puppy",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.2,
    "demand": 2,
    "emoji": "🐶",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 113,
    "name": "Bunny",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.0,
    "demand": 1,
    "emoji": "🐰",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 114,
    "name": "Chick",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.7,
    "demand": 1,
    "emoji": "🐥",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 115,
    "name": "Cockatoo",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.1,
    "demand": 1,
    "emoji": "🦜",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 116,
    "name": "Raccoon",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.3,
    "demand": 1,
    "emoji": "🦝",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 117,
    "name": "Fennec Fox",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.5,
    "demand": 2,
    "emoji": "🦊",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 118,
    "name": "Skunk",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.9,
    "demand": 1,
    "emoji": "🦨",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 119,
    "name": "Armadillo",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 0.95,
    "demand": 1,
    "emoji": "🦔",
    "egg": "Safari Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 120,
    "name": "Capybara",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.6,
    "demand": 2,
    "emoji": "🐹",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 121,
    "name": "Snowman Cub",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.2,
    "demand": 1,
    "emoji": "⛄",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 122,
    "name": "Snowy Owl Chick",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.1,
    "demand": 1,
    "emoji": "🦉",
    "egg": "Christmas Event",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 123,
    "name": "Lunar Mouse",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.0,
    "demand": 1,
    "emoji": "🐭",
    "egg": "Year of the Rat",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 124,
    "name": "Cyber Bunny",
    "category": "Pet",
    "rarity": "Uncommon",
    "value": 1.3,
    "demand": 1,
    "emoji": "🤖",
    "egg": "Cyber Egg",
    "variant": true,
    "obtainable": false,
    "notes": "No longer obtainable"
  },
  {
    "id": 125,
    "name": "Cow (Common)",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.2,
    "demand": 1,
    "emoji": "🐮",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 126,
    "name": "Chicken",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.18,
    "demand": 1,
    "emoji": "🐔",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 127,
    "name": "Pig",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.2,
    "demand": 1,
    "emoji": "🐷",
    "egg": "Farm Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 128,
    "name": "Spider",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.15,
    "demand": 1,
    "emoji": "🕷️",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 129,
    "name": "Crab (Common)",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.17,
    "demand": 1,
    "emoji": "🦀",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 130,
    "name": "Royal Pup",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.22,
    "demand": 1,
    "emoji": "🐶",
    "egg": "Royal Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 131,
    "name": "Iguana",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.16,
    "demand": 1,
    "emoji": "🦎",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 132,
    "name": "Mouse",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.14,
    "demand": 1,
    "emoji": "🐭",
    "egg": "Pet Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 133,
    "name": "Dingo",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.2,
    "demand": 1,
    "emoji": "🐕",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 134,
    "name": "Bandicoot",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.18,
    "demand": 1,
    "emoji": "🐀",
    "egg": "Aussie Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 135,
    "name": "Saltwater Crocodile",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.25,
    "demand": 1,
    "emoji": "🐊",
    "egg": "Jungle Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 136,
    "name": "Starfish",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.13,
    "demand": 1,
    "emoji": "⭐",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 137,
    "name": "Clownfish",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.15,
    "demand": 1,
    "emoji": "🐠",
    "egg": "Ocean Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 138,
    "name": "Mammoth Hatchling",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.2,
    "demand": 1,
    "emoji": "🦣",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 139,
    "name": "Stegosaurus Hatchling",
    "category": "Pet",
    "rarity": "Common",
    "value": 0.2,
    "demand": 1,
    "emoji": "🦕",
    "egg": "Fossil Egg",
    "variant": true,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 140,
    "name": "Cracked Egg",
    "category": "Egg",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 141,
    "name": "Pet Egg",
    "category": "Egg",
    "rarity": null,
    "value": 0.5,
    "demand": 2,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 142,
    "name": "Royal Egg",
    "category": "Egg",
    "rarity": null,
    "value": 6,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 143,
    "name": "Farm Egg",
    "category": "Egg",
    "rarity": null,
    "value": 1.5,
    "demand": 2,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 144,
    "name": "Aussie Egg",
    "category": "Egg",
    "rarity": null,
    "value": 8,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 145,
    "name": "Safari Egg",
    "category": "Egg",
    "rarity": null,
    "value": 30,
    "demand": 4,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 146,
    "name": "Jungle Egg",
    "category": "Egg",
    "rarity": null,
    "value": 22,
    "demand": 4,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 147,
    "name": "Fossil Egg",
    "category": "Egg",
    "rarity": null,
    "value": 10,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 148,
    "name": "Ocean Egg",
    "category": "Egg",
    "rarity": null,
    "value": 12,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 149,
    "name": "Monkey Fancy Egg",
    "category": "Egg",
    "rarity": null,
    "value": 15,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 150,
    "name": "Test Egg",
    "category": "Egg",
    "rarity": null,
    "value": 60,
    "demand": 4,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 151,
    "name": "Diamond Egg (660 days)",
    "category": "Egg",
    "rarity": null,
    "value": 90,
    "demand": 4,
    "emoji": "💎",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 152,
    "name": "Golden Egg",
    "category": "Egg",
    "rarity": null,
    "value": 40,
    "demand": 4,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 153,
    "name": "Cyber Egg",
    "category": "Egg",
    "rarity": null,
    "value": 18,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 154,
    "name": "Galaxy Egg",
    "category": "Egg",
    "rarity": null,
    "value": 25,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 155,
    "name": "Mythic Egg",
    "category": "Egg",
    "rarity": null,
    "value": 35,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 156,
    "name": "Bakery Egg",
    "category": "Egg",
    "rarity": null,
    "value": 28,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 157,
    "name": "Camp Egg",
    "category": "Egg",
    "rarity": null,
    "value": 20,
    "demand": 3,
    "emoji": "🥚",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 158,
    "name": "Halloween Egg 2019",
    "category": "Egg",
    "rarity": null,
    "value": 50,
    "demand": 4,
    "emoji": "🎃",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 159,
    "name": "Christmas Egg 2019",
    "category": "Egg",
    "rarity": null,
    "value": 45,
    "demand": 4,
    "emoji": "🎄",
    "egg": null,
    "variant": false,
    "obtainable": false,
    "notes": ""
  },
  {
    "id": 160,
    "name": "Classic Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🚗",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 161,
    "name": "Pickup Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.4,
    "demand": 1,
    "emoji": "🛻",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 162,
    "name": "Monster Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 1.2,
    "demand": 2,
    "emoji": "🚙",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 163,
    "name": "Tractor",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.6,
    "demand": 1,
    "emoji": "🚜",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 164,
    "name": "Royal Carriage",
    "category": "Vehicle",
    "rarity": null,
    "value": 3.5,
    "demand": 2,
    "emoji": "🛞",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 165,
    "name": "Hot Air Balloon",
    "category": "Vehicle",
    "rarity": null,
    "value": 2.8,
    "demand": 2,
    "emoji": "🎈",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 166,
    "name": "Cruise Ship",
    "category": "Vehicle",
    "rarity": null,
    "value": 8,
    "demand": 3,
    "emoji": "🚢",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 167,
    "name": "Helicopter",
    "category": "Vehicle",
    "rarity": null,
    "value": 4.5,
    "demand": 2,
    "emoji": "🚁",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 168,
    "name": "Jet",
    "category": "Vehicle",
    "rarity": null,
    "value": 12,
    "demand": 3,
    "emoji": "✈️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 169,
    "name": "Submarine",
    "category": "Vehicle",
    "rarity": null,
    "value": 6,
    "demand": 2,
    "emoji": "🛥️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 170,
    "name": "Race Car",
    "category": "Vehicle",
    "rarity": null,
    "value": 2.2,
    "demand": 2,
    "emoji": "🏎️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 171,
    "name": "Limousine",
    "category": "Vehicle",
    "rarity": null,
    "value": 5,
    "demand": 2,
    "emoji": "🚘",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 172,
    "name": "Tour Bus",
    "category": "Vehicle",
    "rarity": null,
    "value": 3.8,
    "demand": 1,
    "emoji": "🚌",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 173,
    "name": "Ice Cream Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 2.5,
    "demand": 2,
    "emoji": "🍦",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 174,
    "name": "Pirate Ship",
    "category": "Vehicle",
    "rarity": null,
    "value": 9,
    "demand": 3,
    "emoji": "🏴‍☠️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 175,
    "name": "UFO",
    "category": "Vehicle",
    "rarity": null,
    "value": 14,
    "demand": 3,
    "emoji": "🛸",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 176,
    "name": "Rocket",
    "category": "Vehicle",
    "rarity": null,
    "value": 16,
    "demand": 3,
    "emoji": "🚀",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 177,
    "name": "Snowplow",
    "category": "Vehicle",
    "rarity": null,
    "value": 1.8,
    "demand": 1,
    "emoji": "🚛",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 178,
    "name": "Golf Cart",
    "category": "Vehicle",
    "rarity": null,
    "value": 0.8,
    "demand": 1,
    "emoji": "🛺",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 179,
    "name": "Fire Truck",
    "category": "Vehicle",
    "rarity": null,
    "value": 1.5,
    "demand": 1,
    "emoji": "🚒",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 180,
    "name": "Classic Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 181,
    "name": "Twin Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.5,
    "demand": 1,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 182,
    "name": "Pet Carriage Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 1.2,
    "demand": 1,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 183,
    "name": "Royal Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 2.5,
    "demand": 2,
    "emoji": "👑",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 184,
    "name": "Sports Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.8,
    "demand": 1,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 185,
    "name": "Glam Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 1.8,
    "demand": 2,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 186,
    "name": "Camping Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 0.9,
    "demand": 1,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 187,
    "name": "Holiday Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 2.0,
    "demand": 2,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 188,
    "name": "Galaxy Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 3.2,
    "demand": 2,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 189,
    "name": "Vintage Stroller",
    "category": "Stroller",
    "rarity": null,
    "value": 1.0,
    "demand": 1,
    "emoji": "👶",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 190,
    "name": "Bouncy Ball",
    "category": "Toy",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "⚽",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 191,
    "name": "Pet Toy Bone",
    "category": "Toy",
    "rarity": null,
    "value": 0.04,
    "demand": 1,
    "emoji": "🦴",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 192,
    "name": "Magic Wand",
    "category": "Toy",
    "rarity": null,
    "value": 0.6,
    "demand": 2,
    "emoji": "🪄",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 193,
    "name": "Royal Wand",
    "category": "Toy",
    "rarity": null,
    "value": 1.5,
    "demand": 2,
    "emoji": "🪄",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 194,
    "name": "Guitar",
    "category": "Toy",
    "rarity": null,
    "value": 0.7,
    "demand": 1,
    "emoji": "🎸",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 195,
    "name": "Drum Set",
    "category": "Toy",
    "rarity": null,
    "value": 0.9,
    "demand": 1,
    "emoji": "🥁",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 196,
    "name": "Piano",
    "category": "Toy",
    "rarity": null,
    "value": 1.1,
    "demand": 1,
    "emoji": "🎹",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 197,
    "name": "Trumpet",
    "category": "Toy",
    "rarity": null,
    "value": 0.6,
    "demand": 1,
    "emoji": "🎺",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 198,
    "name": "Violin",
    "category": "Toy",
    "rarity": null,
    "value": 0.8,
    "demand": 1,
    "emoji": "🎻",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 199,
    "name": "Kite",
    "category": "Toy",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🪁",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 200,
    "name": "Skateboard",
    "category": "Toy",
    "rarity": null,
    "value": 0.4,
    "demand": 1,
    "emoji": "🛹",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 201,
    "name": "Yo-Yo",
    "category": "Toy",
    "rarity": null,
    "value": 0.15,
    "demand": 1,
    "emoji": "🪀",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 202,
    "name": "Frisbee",
    "category": "Toy",
    "rarity": null,
    "value": 0.1,
    "demand": 1,
    "emoji": "🥏",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 203,
    "name": "Pet Brush",
    "category": "Toy",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🧹",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 204,
    "name": "Bubble Wand",
    "category": "Toy",
    "rarity": null,
    "value": 0.25,
    "demand": 1,
    "emoji": "🫧",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 205,
    "name": "Fishing Rod",
    "category": "Toy",
    "rarity": null,
    "value": 0.35,
    "demand": 1,
    "emoji": "🎣",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 206,
    "name": "Hoverboard",
    "category": "Toy",
    "rarity": null,
    "value": 1.8,
    "demand": 2,
    "emoji": "🛹",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 207,
    "name": "Glow Stick Wand",
    "category": "Toy",
    "rarity": null,
    "value": 0.5,
    "demand": 1,
    "emoji": "✨",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 208,
    "name": "Royal Scepter",
    "category": "Toy",
    "rarity": null,
    "value": 2.2,
    "demand": 2,
    "emoji": "👑",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 209,
    "name": "Test Wand",
    "category": "Toy",
    "rarity": null,
    "value": 4,
    "demand": 2,
    "emoji": "🪄",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 210,
    "name": "Apple",
    "category": "Food",
    "rarity": null,
    "value": 0.01,
    "demand": 1,
    "emoji": "🍎",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 211,
    "name": "Cake Slice",
    "category": "Food",
    "rarity": null,
    "value": 0.04,
    "demand": 1,
    "emoji": "🍰",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 212,
    "name": "Pizza Slice",
    "category": "Food",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🍕",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 213,
    "name": "Ice Cream Cone",
    "category": "Food",
    "rarity": null,
    "value": 0.04,
    "demand": 1,
    "emoji": "🍦",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 214,
    "name": "Birthday Cake",
    "category": "Food",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🎂",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 215,
    "name": "Donut",
    "category": "Food",
    "rarity": null,
    "value": 0.03,
    "demand": 1,
    "emoji": "🍩",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 216,
    "name": "Taco",
    "category": "Food",
    "rarity": null,
    "value": 0.03,
    "demand": 1,
    "emoji": "🌮",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 217,
    "name": "Sushi Platter",
    "category": "Food",
    "rarity": null,
    "value": 0.2,
    "demand": 1,
    "emoji": "🍣",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 218,
    "name": "Hot Dog",
    "category": "Food",
    "rarity": null,
    "value": 0.03,
    "demand": 1,
    "emoji": "🌭",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 219,
    "name": "Cookie",
    "category": "Food",
    "rarity": null,
    "value": 0.02,
    "demand": 1,
    "emoji": "🍪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 220,
    "name": "Watermelon Slice",
    "category": "Food",
    "rarity": null,
    "value": 0.02,
    "demand": 1,
    "emoji": "🍉",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 221,
    "name": "Gingerbread Cookie",
    "category": "Food",
    "rarity": null,
    "value": 0.1,
    "demand": 1,
    "emoji": "🍪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 222,
    "name": "Garden Gnome",
    "category": "Gnome",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🧑‍🌾",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 223,
    "name": "Golden Gnome",
    "category": "Gnome",
    "rarity": null,
    "value": 1.5,
    "demand": 2,
    "emoji": "🏆",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 224,
    "name": "Holiday Gnome",
    "category": "Gnome",
    "rarity": null,
    "value": 0.8,
    "demand": 1,
    "emoji": "🎄",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 225,
    "name": "Beach Gnome",
    "category": "Gnome",
    "rarity": null,
    "value": 0.5,
    "demand": 1,
    "emoji": "🏖️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 226,
    "name": "Spooky Gnome",
    "category": "Gnome",
    "rarity": null,
    "value": 0.6,
    "demand": 1,
    "emoji": "🎃",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 227,
    "name": "Rainbow Gnome",
    "category": "Gnome",
    "rarity": null,
    "value": 1.0,
    "demand": 1,
    "emoji": "🌈",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 228,
    "name": "Fly Potion",
    "category": "Other",
    "rarity": null,
    "value": 0.3,
    "demand": 2,
    "emoji": "🧪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 229,
    "name": "Ride Potion",
    "category": "Other",
    "rarity": null,
    "value": 0.25,
    "demand": 2,
    "emoji": "🧪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 230,
    "name": "Fly & Ride Potion",
    "category": "Other",
    "rarity": null,
    "value": 0.5,
    "demand": 3,
    "emoji": "🧪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 231,
    "name": "Neon Wing Potion",
    "category": "Other",
    "rarity": null,
    "value": 1.2,
    "demand": 2,
    "emoji": "🧪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 232,
    "name": "Mega Neon Potion",
    "category": "Other",
    "rarity": null,
    "value": 3.5,
    "demand": 2,
    "emoji": "🧪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 233,
    "name": "Age-Up Potion",
    "category": "Other",
    "rarity": null,
    "value": 0.4,
    "demand": 2,
    "emoji": "🧪",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 234,
    "name": "Crown",
    "category": "Other",
    "rarity": null,
    "value": 0.2,
    "demand": 1,
    "emoji": "👑",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 235,
    "name": "Top Hat",
    "category": "Other",
    "rarity": null,
    "value": 0.15,
    "demand": 1,
    "emoji": "🎩",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 236,
    "name": "Wizard Hat",
    "category": "Other",
    "rarity": null,
    "value": 0.3,
    "demand": 1,
    "emoji": "🧙",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 237,
    "name": "Angel Wings",
    "category": "Other",
    "rarity": null,
    "value": 0.9,
    "demand": 2,
    "emoji": "🪽",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 238,
    "name": "Devil Wings",
    "category": "Other",
    "rarity": null,
    "value": 1.0,
    "demand": 2,
    "emoji": "🪽",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 239,
    "name": "Butterfly Wings",
    "category": "Other",
    "rarity": null,
    "value": 0.7,
    "demand": 1,
    "emoji": "🦋",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 240,
    "name": "Pet Sticker Pack",
    "category": "Other",
    "rarity": null,
    "value": 0.05,
    "demand": 1,
    "emoji": "🏷️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 241,
    "name": "Holographic Sticker",
    "category": "Other",
    "rarity": null,
    "value": 0.2,
    "demand": 1,
    "emoji": "✨",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 242,
    "name": "Mansion House",
    "category": "Other",
    "rarity": null,
    "value": 2.5,
    "demand": 1,
    "emoji": "🏠",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 243,
    "name": "Treehouse",
    "category": "Other",
    "rarity": null,
    "value": 1.8,
    "demand": 1,
    "emoji": "🌳",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 244,
    "name": "Beach House",
    "category": "Other",
    "rarity": null,
    "value": 2.0,
    "demand": 1,
    "emoji": "🏖️",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 245,
    "name": "Castle",
    "category": "Other",
    "rarity": null,
    "value": 4.0,
    "demand": 2,
    "emoji": "🏰",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 246,
    "name": "Camper Van House",
    "category": "Other",
    "rarity": null,
    "value": 1.5,
    "demand": 1,
    "emoji": "🚐",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  },
  {
    "id": 247,
    "name": "Igloo House",
    "category": "Other",
    "rarity": null,
    "value": 1.6,
    "demand": 1,
    "emoji": "🧊",
    "egg": null,
    "variant": false,
    "obtainable": true,
    "notes": ""
  }
];
